schema_version: 1

context:
  version: 12.0

package:
  name: iverilog
  version: ${{ version }}

source:
  url: https://github.com/steveicarus/iverilog/archive/v${{ version | replace(".", "_") }}.tar.gz
  sha256: a68cb1ef7c017ef090ebedb2bc3e39ef90ecc70a3400afb4aa94303bc3beaa7d

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
    - if: not win
      then: autoconf
    - if: win
      then:
        - autotools_clang_conda
        - m2-bison
  host:
    - if: not win
      then:
        - gperf >=3
        - bison
        - flex
        - readline
    - if: win
      then:
        - m2-libreadline
        - m2-gperf
        - m2-flex
    - zlib

tests:
  - script:
      - if: unix
        then:
          - test -f "${PREFIX}/bin/iverilog"
          - test -f "${PREFIX}/bin/iverilog-vpi"
          - test -f "${PREFIX}/bin/vvp"
          - test -f "${PREFIX}/lib/libveriuser.a"
          - test -f "${PREFIX}/lib/libvpi.a"
          - test -f "${PREFIX}/lib/ivl/ivl"
          - test -f "${PREFIX}/lib/ivl/ivlpp"
          - test -f "${PREFIX}/lib/ivl/vhdlpp"
      - iverilog -V
      - vvp -V

about:
  license: GPL-2.0-only
  license_file: COPYING
  summary: Icarus Verilog is intended to compile ALL of the Verilog HDL as described in the IEEE-1364 standard.
  homepage: http://iverilog.icarus.com/home

extra:
  recipe-maintainers:
    - tfors
    - carlodri
