schema_version: 1

context:
  version: "13_0"

package:
  name: iverilog
  version: ${{ version }}

source:
  url: https://github.com/steveicarus/iverilog/archive/v${{ version | replace(".", "_") }}.tar.gz
  sha256: c897bbfa9848688982c6d5c30529fc29d68df0b9ff22ffa73bad89db73a7ce49
  patches:
    - if: osx-64
      then:
        - patch_macos_mach-o.patch

build:
  number: 0

requirements:
  build:
    - if: win
      then:
        - ${{ compiler('m2w64_c') }}
        - ${{ compiler('m2w64_cxx') }}
        - ${{ stdlib('m2w64_c') }}
        - m2-autoconf
        - m2-make
        - m2-bash
        - m2-coreutils
        - m2-base
        - m2-sed
        - m2-grep
        - winflexbison
      else:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - make
        - autoconf
  host:
    - zlib
    - if: not win
      then:
        - gperf >=3
        - bison
        - flex
        - readline

tests:
  - script:
      - if: unix
        then:
          - test -f "${PREFIX}/bin/iverilog"
          - test -f "${PREFIX}/bin/iverilog-vpi"
          - test -f "${PREFIX}/bin/vvp"
          - test -f "${PREFIX}/lib/libvpi.a"
          - test -f "${PREFIX}/lib/ivl/ivl"
          - test -f "${PREFIX}/lib/ivl/ivlpp"
          - test -f "${PREFIX}/lib/ivl/vhdlpp"
      - if: win
        then:
          - if not exist "%LIBRARY_BIN%\\iverilog.exe" exit 1
          - if not exist "%LIBRARY_BIN%\\vvp.exe" exit 1
          - if not exist "%LIBRARY_LIB%\\ivl\\ivl.exe" exit 1
          - if not exist "%LIBRARY_LIB%\\ivl\\ivlpp.exe" exit 1
          - if not exist "%LIBRARY_LIB%\\ivl\\vhdlpp.exe" exit 1
          - if not exist "%LIBRARY_LIB%\\libvpi.a" exit 1
      - iverilog -V
      - vvp -V
  - files:
      recipe:
        - tests/hello.v
    script:
      - iverilog -o hello.vvp tests/hello.v
      - vvp hello.vvp
      - if: unix
        then:
          - vvp hello.vvp | grep -q "Hello, iverilog"
        else:
          - vvp hello.vvp | findstr /C:"Hello, iverilog"

about:
  license: GPL-2.0-only
  license_file: COPYING
  summary: Icarus Verilog is intended to compile ALL of the Verilog HDL as described in the IEEE-1364 standard.
  homepage: http://iverilog.icarus.com/home

extra:
  recipe-maintainers:
    - tfors
    - carlodri
