appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: p8jkF0DF/wmj3gd6cceqB3W102fyS9+hMkPBpUih/IyqmyfX6w1xdW1O81A4L4FZwmcJOmD+iolQoAQ06V6/cI93sqW2uR4Mbfe/Mac8sku65E7JEXSIp/tFBJRiXTXZjGTE66sogp70uWJN4Wxixo7VwlOv/rQLuixyD7kS1DVbRPleyIm6KbX+G2RDJnaHZ0OjXE7ci7qbtQa+YDXAOgL5pbawx/TXQQf4MnqFEOOiziIx1+auaO+6A96X34UNcdg5pLKEpjvLQ/eB6lj26KbFvk3L2HH4iDck2x/KsjKSV3ep/eS+3dzNQp4+gMAZy81nPEpVm/qPtwxwlfRI9zy+LrMTN+m9LZGj87HmWymeZ1tdu/gHzchRMvoqAmsgc+gfL0LEZLrbHcHJJ/8ykfG8kVZ9H4vK38t0b5XFQpwarWTdEA/XiKUpuAhOuddf2l13k+fyP1L19tYghxAyBPBY1v+dJveSSvNXUPU/GyakjEOPL/fpCiTm7LwOUiCzyRuhfVKZdDwwCjDXV5r2sncDI9LGsQFoTiSMyIBRmM3MLMvSV4GkO/sD4wzaAvbNeBTaxky3DZUaS3cYoXufHzVR79MGdmUrMvPCky0kqu1YQsUF4OKojZROT/5/OvEq+EchAnIHkhjyohIDSFFntgwzyxsqIwRX18MErv7QwDI=}
